version: '3.9'

services:
    webserver:
        image: nginx:alpine
        container_name: jobtest-webserver
        working_dir: /application
        volumes:
            - "${DOCKER_DEFAULT_VOLUME}:/application"
            - './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - "${DOCKER_WEBSERVER_PORT}:80"
        depends_on:
            - php-fpm

    php-fpm:
        build: docker/php-fpm
        container_name: jobtest-php-fpm
        working_dir: /application
        volumes:
            - "${DOCKER_DEFAULT_VOLUME}:/application"
            - './docker/php-fpm/php-ini-overrides.ini:/etc/php/8.2/fpm/conf.d/99-overrides.ini'

    mysql:
        container_name: jobtest-mysql
        build:
            context: ./docker/mysql
            args:
                - MYSQL_VERSION=8.0
        environment:
            - MYSQL_DATABASE=${DOCKER_MYSQL_DATABASE}
            - MYSQL_PASSWORD=${DOCKER_MYSQL_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DOCKER_MYSQL_ROOT_PASSWORD}
            - TZ=UTC
        volumes:
            - mysql:/var/lib/mysql
            - ./docker/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
        ports:
            - "3306:3306"

    phpmyadmin:
        container_name: jobtest-phpmyadmin
        build: ./docker/phpmyadmin
        environment:
            - PMA_ARBITRARY=1
            - MYSQL_USER=${DOCKER_MYSQL_USER}
            - MYSQL_PASSWORD=${DOCKER_MYSQL_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DOCKER_MYSQL_ROOT_PASSWORD}
        ports:
            - "${DOCKER_PMA_PORT}:80"
        depends_on:
            - mysql

    mailhog:
        image: mailhog/mailhog:latest
        container_name: jobtest-mailhog
        ports:
            - "8025:8025"

    redis:
        build:
            context: ./docker/redis
        container_name: jobtest-redis
        volumes:
            - redis:/data
        depends_on:
            - php-fpm

volumes:
    mysql:
        driver: "local"
    redis:
        driver: "local"
